

# Define a imagem base
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos necessários para o container
COPY ./bin/Debug/net6.0/publish .

# Define o comando de build
CMD ["dotnet", "Sistarefa.dll"]

